### ISSUE TITLE
Is the Socket API Working ?

### ISSUE THREAD

**Issue by sudeepbatra** [Idirect-Tech/Breeze-Java-SDK#6]
Hi was going through the code, is the Socket API working ? livestream connection is opening but for livefeeds url getting an error "Invalid User:The Login Id entered is not valid"

**Comment by ShrikantOneture** [comment]
yes its working, for both the streaming, follow the same steps

**Comment by ShrikantOneture** [comment]
for order streaming has to subscribe like this
breezeConnect.subscribeFeeds(True)
